/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import query.JDlgConsultaCartao_ebg;
import query.JDlgConsultaCliente_ebg;
import query.JDlgConsultaProduto_ebg;
import query.JDlgConsultaUsuario_ebg;
import query.JDlgConsultaVendedor_ebg;

/**
 *
 * @author user
 */
public class JFrmPrincipal_ebg extends javax.swing.JFrame {
       
    /**
     * Creates new form JFrmPrincipal_ebg
     */
    public JFrmPrincipal_ebg() {
         initComponents();
        setTitle("Tela Principal");
        setExtendedState(MAXIMIZED_BOTH);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jBtnToolCliente_ebg = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        jBtnToolProduto_ebg = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        jBtnToolVenda_ebg = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        jSeparator11 = new javax.swing.JToolBar.Separator();
        jBtnToolConsCliente_ebg = new javax.swing.JButton();
        jSeparator9 = new javax.swing.JToolBar.Separator();
        jBtnToolConsProduto_ebg = new javax.swing.JButton();
        jSeparator10 = new javax.swing.JToolBar.Separator();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMnuPrincipal_ebg = new javax.swing.JMenu();
        jMnuClientes_ebg = new javax.swing.JMenuItem();
        jMenuUsuarios_ebg = new javax.swing.JMenuItem();
        jMenuCartao_ebg = new javax.swing.JMenuItem();
        jMenuVendedor_ebg = new javax.swing.JMenuItem();
        jMenuProduto_ebg = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuSair_ebg = new javax.swing.JMenuItem();
        jMnuMovimento_ebg = new javax.swing.JMenu();
        jMnuVendas_ebg = new javax.swing.JMenuItem();
        Vendedor = new javax.swing.JMenu();
        jMnuConsultaCliente_ebg = new javax.swing.JMenuItem();
        jMnuConsultaUsuario_ebg = new javax.swing.JMenuItem();
        jMnuConsultaCartao_ebg = new javax.swing.JMenuItem();
        jMnuConsultaVendedor_ebg = new javax.swing.JMenuItem();
        jMnuConsultaProduto_ebg = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        jToolBar1.add(jSeparator2);

        jBtnToolCliente_ebg.setForeground(new java.awt.Color(0, 51, 51));
        jBtnToolCliente_ebg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/09 - cliente.png"))); // NOI18N
        jBtnToolCliente_ebg.setText("cad.");
        jBtnToolCliente_ebg.setFocusable(false);
        jBtnToolCliente_ebg.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnToolCliente_ebg.setMaximumSize(new java.awt.Dimension(50, 45));
        jBtnToolCliente_ebg.setMinimumSize(new java.awt.Dimension(50, 45));
        jBtnToolCliente_ebg.setPreferredSize(new java.awt.Dimension(50, 45));
        jBtnToolCliente_ebg.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnToolCliente_ebg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnToolCliente_ebgActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnToolCliente_ebg);
        jToolBar1.add(jSeparator3);

        jBtnToolProduto_ebg.setForeground(new java.awt.Color(0, 51, 51));
        jBtnToolProduto_ebg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/14 - compra.png"))); // NOI18N
        jBtnToolProduto_ebg.setText("cad.");
        jBtnToolProduto_ebg.setFocusable(false);
        jBtnToolProduto_ebg.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnToolProduto_ebg.setMaximumSize(new java.awt.Dimension(50, 45));
        jBtnToolProduto_ebg.setMinimumSize(new java.awt.Dimension(50, 45));
        jBtnToolProduto_ebg.setPreferredSize(new java.awt.Dimension(50, 45));
        jBtnToolProduto_ebg.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnToolProduto_ebg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnToolProduto_ebgActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnToolProduto_ebg);
        jToolBar1.add(jSeparator7);

        jBtnToolVenda_ebg.setForeground(new java.awt.Color(0, 51, 51));
        jBtnToolVenda_ebg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/13 - venda.png"))); // NOI18N
        jBtnToolVenda_ebg.setText("cad.");
        jBtnToolVenda_ebg.setFocusable(false);
        jBtnToolVenda_ebg.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnToolVenda_ebg.setMaximumSize(new java.awt.Dimension(50, 45));
        jBtnToolVenda_ebg.setMinimumSize(new java.awt.Dimension(50, 45));
        jBtnToolVenda_ebg.setPreferredSize(new java.awt.Dimension(50, 45));
        jBtnToolVenda_ebg.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnToolVenda_ebg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnToolVenda_ebgActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnToolVenda_ebg);
        jToolBar1.add(jSeparator8);
        jToolBar1.add(jSeparator11);

        jBtnToolConsCliente_ebg.setForeground(new java.awt.Color(0, 102, 102));
        jBtnToolConsCliente_ebg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/09 - cliente.png"))); // NOI18N
        jBtnToolConsCliente_ebg.setText("cons.");
        jBtnToolConsCliente_ebg.setFocusable(false);
        jBtnToolConsCliente_ebg.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnToolConsCliente_ebg.setMaximumSize(new java.awt.Dimension(50, 45));
        jBtnToolConsCliente_ebg.setMinimumSize(new java.awt.Dimension(50, 45));
        jBtnToolConsCliente_ebg.setPreferredSize(new java.awt.Dimension(50, 45));
        jBtnToolConsCliente_ebg.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnToolConsCliente_ebg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnToolConsCliente_ebgActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnToolConsCliente_ebg);
        jToolBar1.add(jSeparator9);

        jBtnToolConsProduto_ebg.setForeground(new java.awt.Color(0, 102, 102));
        jBtnToolConsProduto_ebg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/14 - compra.png"))); // NOI18N
        jBtnToolConsProduto_ebg.setText("cons.");
        jBtnToolConsProduto_ebg.setFocusable(false);
        jBtnToolConsProduto_ebg.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnToolConsProduto_ebg.setMaximumSize(new java.awt.Dimension(50, 45));
        jBtnToolConsProduto_ebg.setMinimumSize(new java.awt.Dimension(50, 45));
        jBtnToolConsProduto_ebg.setPreferredSize(new java.awt.Dimension(50, 45));
        jBtnToolConsProduto_ebg.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnToolConsProduto_ebg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnToolConsProduto_ebgActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnToolConsProduto_ebg);
        jToolBar1.add(jSeparator10);

        jMnuPrincipal_ebg.setMnemonic('P');
        jMnuPrincipal_ebg.setText("Principal");

        jMnuClientes_ebg.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMnuClientes_ebg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/09 - cliente.png"))); // NOI18N
        jMnuClientes_ebg.setText("Clientes");
        jMnuClientes_ebg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuClientes_ebgActionPerformed(evt);
            }
        });
        jMnuPrincipal_ebg.add(jMnuClientes_ebg);

        jMenuUsuarios_ebg.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jMenuUsuarios_ebg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/08 - usuario.png"))); // NOI18N
        jMenuUsuarios_ebg.setMnemonic('U');
        jMenuUsuarios_ebg.setText("Usuários");
        jMenuUsuarios_ebg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuUsuarios_ebgActionPerformed(evt);
            }
        });
        jMnuPrincipal_ebg.add(jMenuUsuarios_ebg);

        jMenuCartao_ebg.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        jMenuCartao_ebg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/11 - cartao.png"))); // NOI18N
        jMenuCartao_ebg.setText("Cartão");
        jMenuCartao_ebg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCartao_ebgActionPerformed(evt);
            }
        });
        jMnuPrincipal_ebg.add(jMenuCartao_ebg);

        jMenuVendedor_ebg.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        jMenuVendedor_ebg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/12 - caixa.png"))); // NOI18N
        jMenuVendedor_ebg.setText("Vendedor");
        jMenuVendedor_ebg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuVendedor_ebgActionPerformed(evt);
            }
        });
        jMnuPrincipal_ebg.add(jMenuVendedor_ebg);

        jMenuProduto_ebg.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuProduto_ebg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/14 - compra.png"))); // NOI18N
        jMenuProduto_ebg.setText("Produto");
        jMenuProduto_ebg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuProduto_ebgActionPerformed(evt);
            }
        });
        jMnuPrincipal_ebg.add(jMenuProduto_ebg);
        jMnuPrincipal_ebg.add(jSeparator1);

        jMenuSair_ebg.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuSair_ebg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/03 - exit.png"))); // NOI18N
        jMenuSair_ebg.setText("Sair");
        jMenuSair_ebg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSair_ebgActionPerformed(evt);
            }
        });
        jMnuPrincipal_ebg.add(jMenuSair_ebg);

        jMenuBar1.add(jMnuPrincipal_ebg);

        jMnuMovimento_ebg.setText("Movimento");

        jMnuVendas_ebg.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMnuVendas_ebg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/13 - venda.png"))); // NOI18N
        jMnuVendas_ebg.setText("Vendas");
        jMnuVendas_ebg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuVendas_ebgActionPerformed(evt);
            }
        });
        jMnuMovimento_ebg.add(jMnuVendas_ebg);

        jMenuBar1.add(jMnuMovimento_ebg);

        Vendedor.setText("Consulta");

        jMnuConsultaCliente_ebg.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMnuConsultaCliente_ebg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/09 - cliente.png"))); // NOI18N
        jMnuConsultaCliente_ebg.setText("Clientes");
        jMnuConsultaCliente_ebg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuConsultaCliente_ebgActionPerformed(evt);
            }
        });
        Vendedor.add(jMnuConsultaCliente_ebg);

        jMnuConsultaUsuario_ebg.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMnuConsultaUsuario_ebg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/08 - usuario.png"))); // NOI18N
        jMnuConsultaUsuario_ebg.setText("Usuarios");
        jMnuConsultaUsuario_ebg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuConsultaUsuario_ebgActionPerformed(evt);
            }
        });
        Vendedor.add(jMnuConsultaUsuario_ebg);

        jMnuConsultaCartao_ebg.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMnuConsultaCartao_ebg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/11 - cartao.png"))); // NOI18N
        jMnuConsultaCartao_ebg.setText("Cartão");
        jMnuConsultaCartao_ebg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuConsultaCartao_ebgActionPerformed(evt);
            }
        });
        Vendedor.add(jMnuConsultaCartao_ebg);

        jMnuConsultaVendedor_ebg.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMnuConsultaVendedor_ebg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/13 - venda.png"))); // NOI18N
        jMnuConsultaVendedor_ebg.setText("Vendedor");
        jMnuConsultaVendedor_ebg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuConsultaVendedor_ebgActionPerformed(evt);
            }
        });
        Vendedor.add(jMnuConsultaVendedor_ebg);

        jMnuConsultaProduto_ebg.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMnuConsultaProduto_ebg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/14 - compra.png"))); // NOI18N
        jMnuConsultaProduto_ebg.setText("Produto");
        jMnuConsultaProduto_ebg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuConsultaProduto_ebgActionPerformed(evt);
            }
        });
        Vendedor.add(jMnuConsultaProduto_ebg);

        jMenuBar1.add(Vendedor);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMnuClientes_ebgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuClientes_ebgActionPerformed
        // TODO add your handling code here:
        JDlgCliente_ebg jDlgCliente_ebg = new JDlgCliente_ebg(null, true);
        jDlgCliente_ebg.setVisible(true);
    }//GEN-LAST:event_jMnuClientes_ebgActionPerformed

    private void jMenuUsuarios_ebgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuUsuarios_ebgActionPerformed
        // TODO add your handling code here:
        JDlgUsuario_ebg jDlgUsuario_ebg = new JDlgUsuario_ebg(null, true);
        jDlgUsuario_ebg.setVisible(true);
    }//GEN-LAST:event_jMenuUsuarios_ebgActionPerformed

    private void jMenuCartao_ebgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCartao_ebgActionPerformed
        // TODO add your handling code here:
        JDlgCartao_ebg jDlgCartao_ebg = new JDlgCartao_ebg(null, true);
        jDlgCartao_ebg.setVisible(true);
    }//GEN-LAST:event_jMenuCartao_ebgActionPerformed

    private void jMenuVendedor_ebgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuVendedor_ebgActionPerformed
        // TODO add your handling code here:
        JDlgVendedor_ebg jDlgVendedor_ebg = new JDlgVendedor_ebg(null, true);
        jDlgVendedor_ebg.setVisible(true);
    }//GEN-LAST:event_jMenuVendedor_ebgActionPerformed

    private void jMenuProduto_ebgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuProduto_ebgActionPerformed
        JDlgProduto_ebg jDlgProduto_ebg = new JDlgProduto_ebg(null, true);
        jDlgProduto_ebg.setVisible(true);
    }//GEN-LAST:event_jMenuProduto_ebgActionPerformed

    private void jMenuSair_ebgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSair_ebgActionPerformed
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuSair_ebgActionPerformed

    private void jMnuVendas_ebgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuVendas_ebgActionPerformed
        // TODO add your handling code here:
        JDlgVenda_ebg jDlgVendas_ebg = new JDlgVenda_ebg(null, true);
        jDlgVendas_ebg.setVisible(true);
    }//GEN-LAST:event_jMnuVendas_ebgActionPerformed

    private void jBtnToolCliente_ebgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnToolCliente_ebgActionPerformed
        JDlgCliente_ebg jDlgCliente_ebg = new JDlgCliente_ebg(null, true);
        jDlgCliente_ebg.setVisible(true);
    }//GEN-LAST:event_jBtnToolCliente_ebgActionPerformed

    private void jBtnToolProduto_ebgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnToolProduto_ebgActionPerformed
        JDlgProduto_ebg jDlgProduto_ebg = new JDlgProduto_ebg(null, true);
        jDlgProduto_ebg.setVisible(true);
    }//GEN-LAST:event_jBtnToolProduto_ebgActionPerformed

    private void jMnuConsultaCliente_ebgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuConsultaCliente_ebgActionPerformed
        query.JDlgConsultaCliente_ebg jDlgConsultaCliente_ebg = new JDlgConsultaCliente_ebg(null, true);
        jDlgConsultaCliente_ebg.setVisible(true);
    }//GEN-LAST:event_jMnuConsultaCliente_ebgActionPerformed

    private void jMnuConsultaVendedor_ebgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuConsultaVendedor_ebgActionPerformed
        query.JDlgConsultaVendedor_ebg jDlgConsultaVendedor_ebg = new JDlgConsultaVendedor_ebg(null, true);
        jDlgConsultaVendedor_ebg.setVisible(true);
    }//GEN-LAST:event_jMnuConsultaVendedor_ebgActionPerformed

    private void jMnuConsultaUsuario_ebgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuConsultaUsuario_ebgActionPerformed
        query.JDlgConsultaUsuario_ebg jDlgConsultaUsuario_ebg = new JDlgConsultaUsuario_ebg(null, true);
        jDlgConsultaUsuario_ebg.setVisible(true);
    }//GEN-LAST:event_jMnuConsultaUsuario_ebgActionPerformed

    private void jMnuConsultaCartao_ebgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuConsultaCartao_ebgActionPerformed
        query.JDlgConsultaCartao_ebg jDlgConsultaCartao_ebg = new JDlgConsultaCartao_ebg(null, true);
        jDlgConsultaCartao_ebg.setVisible(true);
    }//GEN-LAST:event_jMnuConsultaCartao_ebgActionPerformed

    private void jMnuConsultaProduto_ebgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuConsultaProduto_ebgActionPerformed
        query.JDlgConsultaProduto_ebg jDlgConsultaProduto_ebg = new JDlgConsultaProduto_ebg(null, true);
        jDlgConsultaProduto_ebg.setVisible(true);
    }//GEN-LAST:event_jMnuConsultaProduto_ebgActionPerformed

    private void jBtnToolConsProduto_ebgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnToolConsProduto_ebgActionPerformed
        query.JDlgConsultaProduto_ebg jDlgConsultaProduto_ebg = new JDlgConsultaProduto_ebg(null, true);
        jDlgConsultaProduto_ebg.setVisible(true);
    }//GEN-LAST:event_jBtnToolConsProduto_ebgActionPerformed

    private void jBtnToolConsCliente_ebgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnToolConsCliente_ebgActionPerformed
        query.JDlgConsultaUsuario_ebg jDlgConsultaUsuario_ebg = new JDlgConsultaUsuario_ebg(null, true);
        jDlgConsultaUsuario_ebg.setVisible(true);
    }//GEN-LAST:event_jBtnToolConsCliente_ebgActionPerformed

    private void jBtnToolVenda_ebgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnToolVenda_ebgActionPerformed
        JDlgVenda_ebg jDlgVendas_ebg = new JDlgVenda_ebg(null, true);
        jDlgVendas_ebg.setVisible(true);
    }//GEN-LAST:event_jBtnToolVenda_ebgActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal_ebg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal_ebg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal_ebg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal_ebg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmPrincipal_ebg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Vendedor;
    private javax.swing.JButton jBtnToolCliente_ebg;
    private javax.swing.JButton jBtnToolConsCliente_ebg;
    private javax.swing.JButton jBtnToolConsProduto_ebg;
    private javax.swing.JButton jBtnToolProduto_ebg;
    private javax.swing.JButton jBtnToolVenda_ebg;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuCartao_ebg;
    private javax.swing.JMenuItem jMenuProduto_ebg;
    private javax.swing.JMenuItem jMenuSair_ebg;
    private javax.swing.JMenuItem jMenuUsuarios_ebg;
    private javax.swing.JMenuItem jMenuVendedor_ebg;
    private javax.swing.JMenuItem jMnuClientes_ebg;
    private javax.swing.JMenuItem jMnuConsultaCartao_ebg;
    private javax.swing.JMenuItem jMnuConsultaCliente_ebg;
    private javax.swing.JMenuItem jMnuConsultaProduto_ebg;
    private javax.swing.JMenuItem jMnuConsultaUsuario_ebg;
    private javax.swing.JMenuItem jMnuConsultaVendedor_ebg;
    private javax.swing.JMenu jMnuMovimento_ebg;
    private javax.swing.JMenu jMnuPrincipal_ebg;
    private javax.swing.JMenuItem jMnuVendas_ebg;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator10;
    private javax.swing.JToolBar.Separator jSeparator11;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar.Separator jSeparator8;
    private javax.swing.JToolBar.Separator jSeparator9;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
