package bean;
// Generated 08/12/2023 16:53:50 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * VendaprodutoEbg generated by hbm2java
 */
@Entity
@Table(name="vendaproduto_ebg"
    ,catalog="db_estefani_gimenez"
)
public class VendaprodutoEbg  implements java.io.Serializable {


     private int idvendaprodutoEbg;
     private ProdutoEbg produtoEbg;
     private VendaEbg vendaEbg;
     private int quantidadeEbg;
     private double valorunitEbg;

    public VendaprodutoEbg() {
    }

	
    public VendaprodutoEbg(ProdutoEbg produtoEbg, VendaEbg vendaEbg, int quantidadeEbg) {
        this.produtoEbg = produtoEbg;
        this.vendaEbg = vendaEbg;
        this.quantidadeEbg = quantidadeEbg;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idvendaproduto_ebg", unique=true, nullable=false)
    public int getIdvendaprodutoEbg() {
        return this.idvendaprodutoEbg;
    }
    
    public void setIdvendaprodutoEbg(int idvendaprodutoEbg) {
        this.idvendaprodutoEbg = idvendaprodutoEbg;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="produto_ebg", nullable=false)
    public ProdutoEbg getProdutoEbg() {
        return this.produtoEbg;
    }
    
    public void setProdutoEbg(ProdutoEbg produtoEbg) {
        this.produtoEbg = produtoEbg;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="fkvenda_ebg", nullable=false)
    public VendaEbg getVendaEbg() {
        return this.vendaEbg;
    }
    
    public void setVendaEbg(VendaEbg vendaEbg) {
        this.vendaEbg = vendaEbg;
    }

    
    @Column(name="quantidade_ebg", nullable=false)
    public int getQuantidadeEbg() {
        return this.quantidadeEbg;
    }
    
    public void setQuantidadeEbg(int quantidadeEbg) {
        this.quantidadeEbg = quantidadeEbg;
    }

    
    @Column(name="valorunit_ebg", precision=10)
    public double getValorunitEbg() {
        return this.valorunitEbg;
    }
    
    public void setValorunitEbg(double valorunitEbg) {
        this.valorunitEbg = valorunitEbg;
    }

}


